[workspace]
members = [
     "crates/tauri-plugin-holochain", 
     "crates/holochain_runtime",
     "crates/mdns"
]
resolver = "2"
# exclude = [
#      "examples/end-user-happ",
#      "examples/holochain-runtime" ,
#      "crates/scaffold-holochain-runtime" , 
#      "crates/scaffold-tauri-happ"
# ]

